from datetime import datetime
from typing import Protocol
from uuid import UUID

from petland.modules.identity.public import Actor
from petland.modules.scheduling.domain.models import (
    Appointment,
    Configuration,
    Event,
    Offer,
    Resource,
    Worker,
)


class ScheduleStore(Protocol):
    def lock(self) -> None: ...
    def audit(self, actor_id: UUID, target_id: UUID, action: str, request_id: str) -> None: ...
    def actor(self, actor_id: UUID) -> Actor: ...
    def customer_for(self, actor_id: UUID, assisted_id: UUID | None) -> UUID: ...
    def offer(self, customer_id: UUID, pet_id: UUID, service_id: UUID) -> Offer: ...
    def validate_pet(self, customer_id: UUID, pet_id: UUID, offer: Offer) -> None: ...
    def configuration(self) -> Configuration: ...
    def save_configuration(self, value: Configuration) -> None: ...
    def workers(self) -> list[Worker]: ...
    def resources(self) -> list[Resource]: ...
    def validate_resource(self, value: Resource) -> None: ...
    def save_resource(self, value: Resource) -> None: ...
    def appointments(self, start: datetime, end: datetime) -> list[Appointment]: ...
    def appointments_page(
        self, customer_id: UUID | None, offset: int, limit: int
    ) -> tuple[list[Appointment], int]: ...
    def get(self, appointment_id: UUID, customer_id: UUID | None) -> Appointment: ...
    def save(self, value: Appointment) -> None: ...
    def events(self, appointment_id: UUID) -> list[Event]: ...
    def record(self, event: Event, appointment: Appointment, request_id: str) -> None: ...
    def replay(
        self, actor_id: UUID, operation: str, key: UUID, signature: str
    ) -> Appointment | None: ...
    def remember(
        self, actor_id: UUID, operation: str, key: UUID, signature: str, result: Appointment
    ) -> None: ...
