from typing import Protocol
from uuid import UUID

from petland.modules.pets.domain.models import Breed, Pet, Species


class PetStore(Protocol):
    def customer_for(self, actor_id: UUID, assisted_id: UUID | None) -> UUID: ...
    def species(self) -> list[Species]: ...
    def breeds(self, species_id: str) -> list[Breed]: ...
    def valid_references(self, species_id: str, breed_id: UUID | None) -> bool: ...
    def list(
        self, customer_id: UUID, archived: bool, offset: int, limit: int
    ) -> tuple[list[Pet], int]: ...
    def get(self, customer_id: UUID, pet_id: UUID, lock: bool = False) -> Pet: ...
    def save(self, pet: Pet) -> None: ...
    def audit(self, actor: UUID, target: UUID, action: str, request_id: str) -> None: ...
