from typing import Protocol
from uuid import UUID

from petland.modules.customers.domain.models import Claim, Customer


class CustomerStore(Protocol):
    def lock_owner(self, user_id: UUID) -> None: ...
    def own(self, user_id: UUID) -> Customer | None: ...
    def get(self, customer_id: UUID, lock: bool = False) -> Customer: ...
    def search(self, query: str, offset: int, limit: int) -> tuple[list[Customer], int]: ...
    def save(self, customer: Customer) -> None: ...
    def claim(self, digest: str) -> Claim | None: ...
    def save_claim(self, claim: Claim) -> None: ...
    def invalidate_claims(self, customer_id: UUID) -> None: ...
    def audit(self, actor: UUID, target: UUID, action: str, request_id: str) -> None: ...


class Tokens(Protocol):
    def new(self) -> str: ...
    def digest(self, value: str) -> str: ...


class Mailer(Protocol):
    def send(self, email: str, purpose: str, token: str) -> None: ...
