from datetime import datetime
from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from petland.modules.identity.domain.models import AccountToken, AuditEvent, Session, User


class IdentityStore(Protocol):
    def audit_page(
        self,
        start: datetime,
        end: datetime,
        action: str,
        actor_id: UUID | None,
        target_id: UUID | None,
        offset: int,
        limit: int,
    ) -> tuple[list[AuditEvent], int]: ...
    def user(
        self, *, user_id: UUID | None = None, email: str | None = None, lock: bool = False
    ) -> User | None: ...
    def save_user(self, user: User) -> None: ...
    def users(self, offset: int, limit: int) -> list[User]: ...
    def admin_count(self) -> int: ...
    def lock_administration(self) -> None: ...
    def session(self, digest: str) -> Session | None: ...
    def sessions(self, user_id: UUID) -> list[Session]: ...
    def save_session(self, session: Session) -> None: ...
    def revoke_sessions(self, user_id: UUID, now: datetime) -> None: ...
    def token(self, digest: str) -> AccountToken | None: ...
    def save_token(self, token: AccountToken) -> None: ...
    def invalidate_tokens(self, user_id: UUID, purpose: str, now: datetime) -> None: ...
    def audit(
        self,
        action: str,
        actor: UUID | None,
        target: UUID | None,
        now: datetime,
        request_id: str,
        result: str = "success",
    ) -> None: ...
    def hit_limit(self, key: str, window: int) -> int: ...
    def prune(self, before: datetime) -> None: ...


class UnitOfWork(Protocol):
    @property
    def store(self) -> IdentityStore: ...

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...


class Passwords(Protocol):
    def validate(self, password: str, email: str) -> None: ...
    def hash(self, password: str) -> str: ...
    def verify(self, hashed: str, password: str) -> bool: ...
    def needs_rehash(self, hashed: str) -> bool: ...
    def dummy_verify(self, password: str) -> None: ...


class Tokens(Protocol):
    def new(self) -> str: ...
    def digest(self, value: str) -> str: ...
    def csrf(self, session_token: str) -> str: ...
    def equal(self, left: str, right: str) -> bool: ...


class Mailer(Protocol):
    def send(self, email: str, purpose: str, token: str) -> None: ...
