from typing import Protocol
from uuid import UUID

from petland.modules.catalog.domain.models import Service
from petland.modules.pets.public import Size


class CatalogStore(Protocol):
    def authorize_write(self, actor_id: UUID) -> None: ...
    def species_exist(self, species_ids: list[str]) -> bool: ...
    def get(self, service_id: UUID, lock: bool = False) -> Service: ...
    def list(
        self, public: bool, species_id: str | None, size: Size | None, offset: int, limit: int
    ) -> tuple[list[Service], int]: ...
    def save(self, service: Service) -> None: ...
    def audit(self, actor: UUID, target: UUID, action: str, request_id: str) -> None: ...
